tenjin:
  image: "yethitech/tenjin-enterprise"  # Default image name
  imageTag: "4.11.2"
  persistence:
    size: "5Gi" # Size of the storage
    storageClassName: "standard" # Name of the storage class (adjust based on your cluster)
  service:
    type: NodePort
    port: 8080
tenjin_ai:
  image: "yethitech/ai-testcase-generation"  # Default image name
  imageTag: "latest"
busybox:
  image: "busybox:latest"
elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.3"  # Default image name
  config:
    bootstrap_memory_lock: true
    ES_JAVA_OPTS: "-Xms512m -Xmx2G"
  persistence:
    accessModes: ReadWriteOnce
    storageClassName: standard
    size: 5Gi
postgres:
  image: postgres:13
  persistence:
    size: 10Gi # Storage size
    accessModes: ReadWriteOnce # Access mode
    storageClassName: standard # StorageClass for dynamic provisioning
environment:
  POSTGRES_DB: tenjin
  POSTGRES_USER: yethi
  POSTGRES_PASSWORD: Yethi123
  DEFAULT_USER_PASSWORD: Welcome@123
  TENJIN_HOST_NAME: tenjin.uat.bankdhofar.com
  TENJIN_ALLOWED_URL: http://localhost

kibana:
  image: "docker.elastic.co/kibana/kibana:8.3.3"

extraManifests: []
# - |
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: my-config
#   data:
#     key: value

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150m" 
  bodySize: "150m"
  services:
    - host: "tenjin.uat.bankdhofar.com"
      paths:
        - path: /
          pathType: Prefix
          serviceName: "{{ .Release.Name }}-tenjin-core"
          servicePort: 8080
    - host: "tenjin-kibana.uat.bankdhofar.com"
      paths:
        - path: /
          pathType: Prefix
          serviceName: "{{ .Release.Name }}-kibana"
          servicePort: 5601
  tls:
    - hosts:
        - "tenjin.uat.bankdhofar.com"
      secretName: tls-uat-bankdhofar-com
    - hosts:
        - "tenjin-kibana.uat.bankdhofar.com"
      secretName: tls-uat-bankdhofar-com
