apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-db-init-job
spec:
  schedule: "0 0 1 1 *"  # Run at 00:00 on Jan 1st every year
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: db-updater
              image: bitnami/postgresql:13
              command:
                - /bin/sh
                - -c
                - |-
                  echo "Waiting for PostgreSQL to be ready...";
                  until pg_isready -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin"; do
                    sleep 5;
                  done;

                  echo "Sleeping extra 20s for services to settle...";
                  sleep 20;

                  export PGPASSWORD="Yethi123"

                  echo "Running new migration queries one by one with delay..."

                  echo "Executing: Insert into tdes_classification_types"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "INSERT INTO tdes_classification_types (id, name, description, icon, classification_type_id) VALUES (-1, 'TTM', 'Test managment folder', 'aiOutlineFolder', 'ttmfolder');"
                  sleep 5

                  echo "Executing: Add output_language to ai_yts_design_transactions"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE ai_yts_design_transactions ADD COLUMN output_language varchar(255) NULL;"
                  sleep 5

                  echo "Executing: Add vector_id to ai_yts_design_transactions"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE ai_yts_design_transactions ADD COLUMN vector_id varchar(255) NULL;"
                  sleep 5

                  echo "Executing: Add parallel_sessions_allowed to application"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE application ADD COLUMN parallel_sessions_allowed bool DEFAULT false NOT NULL;"
                  sleep 5

                  echo "Executing: Update NULL parallel_sessions_allowed to false"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "UPDATE application SET parallel_sessions_allowed = false WHERE parallel_sessions_allowed IS NULL;"
                  sleep 5

                  echo "Executing: Add is_archived to exe_test_runs"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE public.exe_test_runs ADD COLUMN is_archived bool DEFAULT false NOT NULL;"
                  sleep 5

                  echo "Executing: Set STORAGE PLAIN on is_archived in exe_test_runs"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE public.exe_test_runs ALTER COLUMN is_archived SET STORAGE PLAIN;"
                  sleep 5

                  echo "Executing: Make password nullable in email_configuration"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE public.email_configuration ALTER COLUMN \"password\" DROP NOT NULL;"
                  sleep 5

                  echo "Executing: Add authentication_required to email_configuration"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE public.email_configuration ADD COLUMN authentication_required bool NULL;"
                  sleep 5

                  echo "Executing: Set authentication_required = true if rows exist"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "UPDATE public.email_configuration SET authentication_required = true WHERE EXISTS (SELECT 1 FROM public.email_configuration);"
                  sleep 5

                  echo "Executing: Add detail_no to runtime_field_value"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE runtime_field_value ADD COLUMN detail_no VARCHAR(255);"
                  sleep 5

                  echo "Executing: Add detail_no to validation_result"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE validation_result ADD COLUMN detail_no VARCHAR(255);"
                  sleep 5

                  echo "Executing: Update runtime_field_value set detail_no=1 where NULL"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "UPDATE runtime_field_value SET detail_no = '1' WHERE detail_no IS NULL;"
                  sleep 5

                  echo "Executing: Update validation_result set detail_no=1 where NULL"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "UPDATE validation_result SET detail_no = '1' WHERE detail_no IS NULL;"
                  sleep 5

                  echo "✅ All new migration queries executed with delay."
  