apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-db-init-job
spec:
  schedule: "0 0 1 1 *"  # Run at 00:00 on Jan 1st every year
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: db-updater
              image: bitnami/postgresql:13
              command:
                - /bin/sh
                - -c
                - |-
                  echo "Waiting for PostgreSQL to be ready...";
                  until pg_isready -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin"; do
                    sleep 5;
                  done;

                  echo "Sleeping extra 20s for services to settle...";
                  sleep 20;

                  export PGPASSWORD="Yethi123"

                  echo "Running migration queries..."

                  echo "Executing: Add is_deleted to test_case_attempt"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE public.test_case_attempt ADD COLUMN is_deleted bool DEFAULT false NOT NULL;"
                  sleep 5

                  echo "Executing: Add is_deleted to test_step_attempt"
                  psql -h {{ .Release.Name }}-postgres -U "yethi" -d "tenjin" -c "ALTER TABLE public.test_step_attempt ADD COLUMN is_deleted bool DEFAULT false NOT NULL;"
                  sleep 5

                  echo "✅ Migration queries executed successfully."
