apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tenjin-pgadmin-gw
spec:
  gateways:
    - {{ .Values.pgadmin.gateway.namespace | default "istio-system" }}/{{ .Values.pgadmin.gateway.name | default "gw-uat-bankdhofar-com" }}
  hosts:
    - {{ .Values.pgadmin.host | default "tenjin-pg-admin.uat.bankdhofar.com" }}
  http:
    - match:
        - headers:
            host:
              exact: {{ .Values.pgadmin.host | default "tenjin-pg-admin.uat.bankdhofar.com" }}
      route:
        - destination:
            host: tenjin-pgadmin
            port:
              number: 80
      timeout: 300s
