apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenjin-core
  labels:
    app: {{ .Release.Name }}-tenjin-core
spec:
  type: {{ .Values.tenjin.service.type }}
  selector:
    app: tenjin
  ports:
    - name: http-main
      protocol: TCP
      port: {{ .Values.tenjin.service.port }}
      targetPort: 8080
    - name: http-ext
      protocol: TCP
      port: 8090
      targetPort: 8080
